language: node_js
node_js: "12"
before_install:
  - npm i
    
jobs:
  include:
    - stage: Linux & Mac Build
      os: osx
      osx_image: xcode10.2
      env: 
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      before_cache:
        - rm -rf $ELECTRON_BUILDER_CACHE/wine
      script:
        - npm run devInstall:64
        - npm run build
#    - stage: Windows Build
#      os: windows
#      script:
#        - export NPM_CONFIG_PREFIX=C:\\npm_prefix 
#        - export PATH="/c/npm_prefix:$PATH"
#        - npm i -g npm@latest
#        - npm run devInstall
#        - npm run build
    - stage: GitHub Release
      script: 
        - node ci-deploy
      deploy:
        provider: releases
        prerelease: true
        api_key: "$GH_TOKEN"
        cleanup: false
        file:
#          - builds/lightcord-win32-ia32.zip
#          - builds/lightcord-win32.exe
          - builds/lightcord-linux-x64.zip
          - builds/lightcord-darwin.zip
        on:
          tags: true
