language: node_js
node_js: "lts/*"
before_install:
  - npm i -g npm@6.14.6
  - npm i
  
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    
    
jobs:
  include:
    - stage: Linux & Mac Build
      os: osx
      osx_image: xcode10.1
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      script:
        - npm run devInstall:64
        - npm run build
    - stage: Windows Build
      os: windows
      script:
        - npm run devInstall
        - npm run build
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        prerelease: true
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file:
          - builds/lightcord-win32-ia32.zip
          - builds/lightcord-win32.exe
          - builds/lightcord-linux-x64.zip
          - builds/lightcord-darwin-x64.zip
        on:
          tags: true
