language: node_js
node_js: "lts/*"
before_install:
  - npm i -g npm@6.14.6
  - npm i
  - npm run devInstall
  
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    
script: npm run build
